language: javascript

script: mongo test.js

before_install:
  # travis's mongodb service is 2.4, but we need mongodb 3.2+, thus we install our own.
  # https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  - echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  - sudo apt-get update
  - sudo apt-get install -y --force-yes mongodb-org

before_script:
  - sudo service mongod start
  # https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
  - sleep 15

after_script:
  - sudo service mongod stop
